### ISSUE TITLE
CocoaPods error

### ISSUE THREAD

**Issue by sargismkhitaryan** [WellerZhao/EasySip#2]
I want to run your Example code. When I run 'pod install' receive error Unable to find a specification for `EasySip`.

**Comment by WellerZhao** [comment]
You can find the 'EasySip' Library on https://cocoapods.org/

You should try `pod repo` to check your source. 

https://stackoverflow.com/questions/25913733/unable-to-find-a-specification-in-cocoapods
You can try to do:

```
pod repo remove master
pod setup
pod install
```
Or:

```
sudo rm -fr ~/.cocoapods/repos/master
pod setup
pod install
```

**Comment by sargismkhitaryan** [comment]
Thank you a lot. It's help.
